image: continuumio/anaconda3:latest

before_script:
- source /opt/conda/etc/profile.d/conda.sh
- conda env create -f environment.yml
- conda activate osa
- conda install sphinx
- conda install sphinx_rtd_theme
- conda develop .

testcode:
  stage: test
  script:
  - pytest provenance/
  only:
  - branches
  except:
  - master

testdocs:
  stage: test
  script:
  - sphinx-build -b html ./docs public
  only:
  - branches
  except:
  - master

deploydocs:
  stage: deploy
  script:
  - sphinx-build -b html ./docs public
  artifacts:
    paths:
    - public
  only:
  - master
