image: continuumio/miniconda3:latest

stages:
  - test
  - docs
  
before_script:
  - apt-get update && apt-get install -y build-essential
  - source /opt/conda/etc/profile.d/conda.sh
  - conda env create -n osa-ci -f environment.yml
  - conda activate osa-ci
  - pip install -e .

testcode:
  stage: test
  script:
    - pytest -v

deploydocs:
  stage: docs
  script:
    - cd docs && make clean html
