image: continuumio/anaconda3:latest
  
before_script:
- apt-get update && apt-get install -y build-essential
- pip install --upgrade pip
- source /opt/conda/etc/profile.d/conda.sh
- conda env create -f environment.yml
- conda activate osa
- conda install sphinx
- conda install sphinx_rtd_theme
- conda develop .

testcode:
  stage: test
  script:
  - pytest osa/provenance/
  only:
  - branches
  except:
  - master

testdocs:
  stage: test
  script:
  - sphinx-build -b html ./docs ./docs/_build
  only:
  - branches
  except:
  - master

deploydocs:
  stage: deploy
  script:
  - sphinx-build -b html ./docs public ./docs/_build
  only:
  - master
  
