image: continuumio/miniconda3:4.8.2

stages:
  - test
  - docs
  
before_script:
  - ENV PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  - conda env create -f environment.yml
  - conda activate osa
  - conda develop .

testcode:
  stage: test
  script:
  - pytest osa/provenance/

deploydocs:
  stage: docs
  script:
  - cd docs && make clean html
