image: continuumio/miniconda3:latest

stages:
  - test
  - docs
  
before_script:
  - apt-get update && apt-get install -y build-essential
  - source /opt/conda/etc/profile.d/conda.sh
  - conda env create -f environment.yml
  - conda activate osa
  - conda develop .

testcode:
    #  tags:
    #    - kubernetes
  stage: test
  script:
    - pytest

deploydocs:
    #  tags:
    #    - kubernetes
  stage: docs
  script:
    - cd docs && make clean html
