path_classifiers:
  test:
    - "osa/**/test_*.py"
  docs:
    - docs

extraction:
  python:
    python_setup:
      version: 3

    index:
      exclude:
        - dev
        - utils
        - extra
        - cfg