version: 2

conda:
  environment: docs/environment.yml

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  fail_on_warning: true
