name: osa-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  # core dependencies
  - python=3.7
  - conda-build
  - pip
  - ctapipe~=0.10.5
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - gammapy>=0.18
  - h5py
  - joblib
  # dev dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - black
  - isort
  - sphinx
  - sphinx_rtd_theme
  - sphinx-argparse
  - pip:
      - lstchain~=0.7.0
      - pytest_runner
      - pytest-ordering
      - ctapipe_io_lst~=0.9.0
      - sphinx-automodapi
      - sphinx-autoapi
