name: osa-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  # core dependencies
  - python=3.8
  - pip
  - ctapipe~=0.11
  - protozfits=2.0
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - psutil
  - gammapy=0.18
  - h5py
  - joblib
  - traitlets=5.0
  # dev dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - black
  - isort
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-argparse
  - sphinx-autoapi
  - pip:
      - lstchain~=0.8.2
      - pytest_runner
      - pytest-ordering
      - ctapipe_io_lst~=0.13.2
