name: osa-dev
channels:
  - conda-forge
  - default
dependencies:
  # core dependencies
  - python=3.11
  - numpy
  - pip
  - astropy~=5.0
  - ctapipe~=0.19.2
  - protozfits=2.0
  - matplotlib=3.7
  - pyparsing
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - psutil
  - gammapy=1.1
  - h5py
  - joblib~=1.2.0
  - click
  - pymongo
  - scikit-learn=1.2
  - protobuf=3.20
  # dev dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - coverage
  - black
  - isort
  - sphinx=4
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-argparse
  - sphinx-autoapi
  - pip:
      - lstchain==0.10.0
      - pytest_runner
      - pytest-ordering
      - ctapipe_io_lst~=0.21.0
      - ctaplot~=0.6.2
      - pyirf~=0.8.0
