name: osa-dev
channels:
  - conda-forge
  - default
dependencies:
  # core dependencies
  - python=3.8
  - numpy=1.21
  - pip
  - astropy~=4.2
  - ctapipe~=0.12
  - protozfits=2.0
  - matplotlib=3.5
  - pyparsing
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - psutil
  - gammapy=0.19
  - h5py
  - joblib
  - click
  - pymongo
  - scikit-learn=1.0
  # dev dependencies
  - pre-commit
  - pytest
  - pytest-cov
  - coverage=6.2
  - black
  - isort
  - sphinx
  - sphinx_rtd_theme
  - sphinx-automodapi
  - sphinx-argparse
  - sphinx-autoapi
  - pip:
      - lstchain~=0.9.6
      - pytest_runner
      - pytest-ordering
      - ctapipe_io_lst~=0.18.1
      - ctaplot~=0.5.5
      - pyirf~=0.6.0
