name: osa-dev
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  - conda-build
  - pip
  - ctapipe=0.7.0
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - gammapy>=0.17
  - h5py
  - pytest
  - pytest-cov
  - black
  - isort
  - pip:
      #- git+https://github.com/cta-observatory/cta-lstchain.git
      - git+git://github.com/cta-observatory/cta-lstchain
        #- lstchain
      - pytest_runner
      - pytest-ordering
      - git+git://github.com/cta-observatory/ctapipe_io_lst@v0.4.1
