name: osa
channels:
  - default
  - cta-observatory
  - conda-forge
dependencies:
  # core dependencies
  - python=3.7
  - conda-build
  - pip
  - ctapipe=0.8.0
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - gammapy>=0.17
  - h5py
  - joblib
  # dev dependencies
  - pytest
  - pytest-cov
  - black
  - isort
  - sphinx
  - sphinx_rtd_theme
  - sphinx-argparse
  - pip:
      - lstchain
      - pytest_runner
      - pytest-ordering
      - git+git://github.com/cta-observatory/ctapipe_io_lst@v0.5.3
      - sphinx-automodapi
      - autoapi
