name: osa-dev
channels:
  - conda-forge
dependencies:
  # core dependencies
  - python=3.11
  - numpy
  - pip
  - astropy>=6.1,<8
  - ctapipe>=0.25.0
  - matplotlib
  - pyparsing
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - psutil
  - gammapy=1.3
  - h5py
  - joblib~=1.2.0
  - click
  - pymongo
  - scikit-learn=1.6
  - ctapipe_io_lst>=0.26.0,<0.28.0a0
  - ctaplot~=0.6.4
  - pyirf~=0.12.0
  - tenacity
  - pip:
      - lstchain>=0.11.0
  # dev dependencies
  - pytest
  - pytest-cov
  - coverage
  - freezegun
  # formatting dependencies
  - pre-commit
  - black
  - ruff
  # docs dependencies
  - sphinx
  - sphinx-automodapi
  - numpydoc
  - pydata-sphinx-theme
  - sphinx-argparse
