name: osa-dev
channels:
  - conda-forge
dependencies:
  # core dependencies
  - python=3.11
  - numpy
  - pip
  - astropy~=5.0
  - ctapipe~=0.19.2
  - matplotlib=3.7
  - pyparsing
  - prov
  - pyyaml
  - pydot
  - pydotplus
  - psutil
  - gammapy=1.1
  - h5py
  - joblib~=1.2.0
  - click
  - pymongo
  - scikit-learn=1.2
  - protobuf=3.20
  - ctapipe_io_lst=0.22
  - ctaplot~=0.6.4
  - pyirf=0.8
  - lstchain~=0.10.0
  - tenacity
  # dev dependencies
  - pytest
  - pytest-cov
  - coverage
  - freezegun
  # formatting dependencies
  - pre-commit
  - black
  - ruff
  # docs dependencies
  - sphinx
  - sphinx-automodapi
  - numpydoc
  - pydata-sphinx-theme
  - sphinx-argparse
